//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KwikScaf2007.rc
//
#define IDS_PROJNAME                    100
#define IDD_BAY_DETAILS_DIALOG          101
#define IDD_LIFT_DETAILS_DIALOG         103
#define IDD_LISTPAGE2                   104
#define IDD_LISTSETUP                   105
#define IDD_PRINT_STATUS                106
#define IDC_SCROLLBAR1                  107
#define IDC_MSG_BOX_EDIT1               109
#define IDD_DIALOG1                     114
#define IDD_BAY_PROPERTIES_DIALOG       117
#define IDD_AUTOBUILD_PROPERTIES_DIALOG 122
#define IDD_BOM_EXTRA_DIALOG            123
#define IDD_JOB_DETAILS_DIALOG          124
#define IDB_NS_ONE_PLANK_BITMAP         130
#define IDB_NS_TWO_PLANKS_BITMAP        131
#define IDB_NS_THREE_PLANKS_BITMAP      132
#define IDB_NS_NO_PLANKS_BITMAP         134
#define IDB_EW_TWO_PLANKS_BITMAP        136
#define IDB_EW_ONE_PLANK_BITMAP         137
#define IDB_EW_THREE_PLANKS_BITMAP      138
#define IDB_EW_NO_PLANKS_BITMAP         139
#define IDD_BOM_SUMMARY_DIALOG          140
#define IDD_BOM_STAGE_LEVEL_DIALOG      141
#define IDR_PRINT                       147
#define IDC_HANDCUR                     149
#define IDD_LISTPAGE1                   150
#define IDB_PAGE                        151
#define IDD_SET_STAGES_DIALOG           154
#define IDD_STANDARD_HEIGHT_DIALOG      156
#define IDD_ASSIGN_STAGE_DALOG          159
#define IDD_SET_RL_DLG                  161
#define IDB_RL_CHANGE_01                162
#define IDD_EDIT_STANDARDS              172
#define IDR_BAYPROPERTIES_TOOLBAR       175
#define IDD_SHOW_COMPONENT_TYPES        177
#define IDD_HELP_ABOUT                  178
#define IDB_HELP_ABOUT_PIC01            183
#define IDD_VISUAL_MILLS_TYPE           184
#define IDD_REVISION_NOTES              189
#define IDD_VISUAL_COMPONENT_DETAILS_DIALOG 195
#define IDC_LOADING_WAIT                199
#define IDD_KWIKSCAF_PROGRESS           203
#define IDD_SELECT_VISIBLE_PART_NUMBER_DLG 205
#define IDB_VC_LOGO_EDITOR              210
#define IDB_VC_LOGO_INSERT              211
#define IDD_M2_OR_PER_ROLL_DLG          212
#define IDD_ADJUST_COMPONENT_DETAILS    213
#define IDD_SHOW_STAGE_LEVEL            214
#define IDD_KWIKSCAF_COMPONENT_EDITOR   215
#define IDD_BOM_STAGE_LEVEL_DIALOG1     216
#define IDD_BOM_SUMMARY_DIALOG1         217
#define IDD_BAY_DETAILS_DIALOG1         218
#define IDD_SET_STAGES_DIALOG1          219
#define IDD_ASSIGN_STAGE_DALOG1         220
#define IDD_LIFT_DETAILS_DIALOG1        221
#define IDC_STAGGERED_HEIGHTS_CHECK     1000
#define IDC_COURSE_FIT_RADIO            1001
#define IDC_FINE_FIT_RADIO              1002
#define IDC_SAME_FIT_RADIO              1003
#define IDC_NW_STANDARD_LBOX            1004
#define IDC_NE_STANDARD_LBOX            1005
#define IDC_NW_STANDARD_EDIT            1012
#define IDC_NE_STANDARD_EDIT            1013
#define IDC_NW_SOLEBOARD_CHECK          1014
#define IDC_NE_SOLEBOARD_CHECK          1015
#define IDC_SW_STANDARD_LBOX            1016
#define IDC_SE_STANDARD_LBOX            1017
#define IDC_SW_STANDARD_EDIT            1018
#define IDC_SE_STANDARD_EDIT            1019
#define IDC_SPIN2                       1020
#define IDC_SW_SOLEBOARD_CHECK          1020
#define IDC_SE_SOLEBOARD_CHECK          1021
#define IDC_SPIN3                       1022
#define IDC_TOP_WORKING_HEIGHT_SPIN     1022
#define IDC_TOP_WORKING_HEIGHT_EDIT     1023
#define IDC_NE_STANDARD_RL              1024
#define IDC_NUMBER_DECKS_EDIT           1025
#define IDC_NUMBER_DECKS_SPIN           1026
#define IDC_NW_STANDARD_RL              1027
#define IDC_SPIN4                       1028
#define IDC_NUMBER_STAGES_EDIT          1028
#define IDC_NUMBER_STAGES_SPIN          1029
#define IDC_SE_STANDARD_RL              1030
#define IDC_STAGE_BRACKET_WIDTHS_COMBO  1031
#define IDC_RAILOPTIONS_HAND_RADIO      1032
#define IDC_HANDOPTIONS_MESH_RADIO      1033
#define IDC_HANDOPTIONS_FULLMESH_RADIO  1034
#define IDC_HANDOPTIONS_SHADECLOTH_CHECK 1035
#define IDC_HANDOPTIONS_CHAIN_CHECK     1036
#define IDC_APPLY_BUTTON                1037
#define IDC_LIFTDETAILS_BUTTON          1038
#define IDC_APPLY_SELECTION_BUTTON      1039
#define IDC_HANDOPTIONS_FULL_MESH_DECKS_ONLY 1041
#define IDC_EDIT_DETAILS_BUTTON         1041
#define IDC_SW_STANDARD_RL              1042
#define IDC_LIFT_SELECTION_COMBO        1056
#define IDC_NW_STAGEBOARD_CHECK         1059
#define IDC_SL_COMMITTED                1062
#define IDC_NE_STAGEBOARD_CHECK         1078
#define IDC_SW_STAGEBOARD_CHECK         1080
#define IDC_SE_STAGEBOARD_CHECK         1082
#define IDC_WEST_HANDRAIL_BUTTON        1084
#define IDC_NORTH_HANDRAIL_BUTTON       1085
#define IDC_SOUTH_HANDRAIL_BUTTON       1086
#define IDC_EAST_HANDRAIL_BUTTON        1087
#define IDC_CHECK14                     1088
#define IDC_CHECK15                     1089
#define IDC_CHECK16                     1090
#define IDC_CHECK17                     1091
#define IDC_DECKING_CHECK               1092
#define IDC_BAY_WIDTH_COMBO2            1093
#define IDC_LEVEL_COMBO                 1093
#define IDC_SETSTAGES_UPPER_LEVEL_COMBO 1093
#define IDC_MATERIAL_TYPE_COMBO         1094
#define IDC_HANDRAIL_STYLE_COMBO        1095
#define IDC_DECK_HEIGHT_EDIT            1096
#define IDC_DECK_HEIGHT_SPIN            1097
#define IDC_LIFT_HEIGHT_COMBO           1098
#define IDC_LIFT_LENGTH_EDIT            1099
#define IDC_LIFT_WIDTH_EDIT             1100
#define IDC_LIFT_STAGE_EDIT             1101
#define IDC_LIFT_LEVEL_EDIT             1102
#define IDC_INSERT_LIFT_BUTTON          1105
#define IDC_DELETE_LIFT_BUTTON          1106
#define IDC_MOVE_LIFT_DOWN              1107
#define IDC_MOVE_LIFT_UP                1108
#define IDC_LABEL2                      1117
#define IDC_LABEL3                      1118
#define IDC_LABEL4                      1119
#define IDC_LABEL5                      1120
#define IDC_LABEL6                      1121
#define IDC_LABEL7                      1122
#define IDC_LABEL8                      1123
#define IDC_LABEL9                      1124
#define IDC_LABEL10                     1125
#define IDC_BAY_WIDTH_COMBO             1146
#define IDC_DECK_EDIT                   1148
#define IDC_ADVANCED_BUTTON             1150
#define IDC_DECK_SPIN                   1151
#define IDC_BAY_LENGTH_COMBO            1152
#define IDC_BAY_DETAILS_BUTTON          1155
#define IDC_AB_EDIT_DETAILS_BUTTON      1156
#define IDC_AB_CLOSE_BUTTON             1157
#define IDC_AB_TIGHT_FIT_RADIO          1158
#define IDC_AB_LOOSE_FIT_RADIO          1159
#define IDC_AB_TIES_EVERY_COMBO         1162
#define IDC_AB_TIES_VERTICALLY_EVERY_EDIT 1163
#define IDC_AB_TIES_VERTICALLY_EVERY_SPIN 1164
#define IDC_AB_TIE_TYPE_COMBO           1165
#define IDC_AB_BRACES_EVERY_COMBO       1166
#define IDC_LIFT_DETAILS_CANCEL_BUTTON  1167
#define IDC_SPIN1                       1168
#define IDC_SPIN5                       1169
#define IDC_COMPONENT_LISTBOX           1169
#define IDC_SPIN6                       1170
#define IDC_SPIN7                       1171
#define IDC_RL_START                    1171
#define IDC_ADD_BUTTON                  1171
#define IDC_RL_START_SPIN               1172
#define IDC_REMOVE_BUTTON               1172
#define IDC_RL_END                      1173
#define IDC_REMOVEALL_DONE              1173
#define IDC_RL_END_SPIN                 1174
#define IDC_QUANTITY_EDIT               1174
#define IDC_DISTANCE_FROM_WALL          1175
#define IDC_DISTANCE_FROM_WALL_SPIN     1176
#define IDC_JOB_DESCRIPTION_EDIT        1176
#define IDC_JOB_DRAFTSMAN_EDIT          1177
#define IDC_JOB_PROJECT_DURATION_EDIT   1178
#define IDC_JOB_BRANCH_COMBO            1180
#define IDC_JOB_REF_NUMBER_EDIT         1181
#define IDC_JOB_MARKETING_NUM_EDIT      1182
#define IDC_JOB_CLIENT_EDIT             1183
#define IDC_JOB_CLIENT_ADDR_EDIT        1184
#define IDC_JOB_CLIENT_ZIP_EDIT         1186
#define IDC_JOB_PHONE_EDIT              1189
#define IDC_JOB_FAX_NUMBER_EDIT         1192
#define IDC_JOB_START_DATETIMEPICKER    1193
#define IDC_JOB_TITLE_EDIT              1194
#define IDC_NORTH_STAGEBOARD_BUTTON     1195
#define IDC_WEST_STAGEBOARD_BUTTON      1196
#define IDC_EAST_STAGEBOARD_BUTTON      1197
#define IDC_SOUTH_STAGEBOARD_BUTTON     1198
#define IDC_OK_BUTTON_CTRL              1199
#define IDC_JOB_CLIENT_COMPANY_EDIT     1200
#define IDC_BOM_SELECTION_LISTBOX_CTRL  1201
#define IDC_BOM_SUMMARY_LISTCTRL        1201
#define IDC_SETSTAGES_LISTBOX           1201
#define IDC_BOM_SELECTED_LISTBOX_CTRL   1202
#define IDC_STOCK_TEST_LISTBOX          1202
#define IDC_STANDARDS_OUTER             1202
#define IDC_SET_AS_DEFAULT              1203
#define IDC_BOMSL_ADD_BUTTON            1203
#define IDC_BOM_EXTRA                   1203
#define IDC_STANDARDS_INNER             1203
#define IDC_BUTTON1                     1203
#define IDC_SETSTAGES_SELECT_BAYS_BUTTON 1203
#define IDC_SHOW_ALL                    1203
#define IDC_OK                          1204
#define IDC_BOMSL_ADD_ALL_BUTTON        1204
#define IDC_COMMIT                      1204
#define IDC_APPLY                       1204
#define IDC_ACF_2D_BROWSE               1204
#define IDC_SETSTAGES_ASSIGN_STAGE_BUTTON 1204
#define IDC_HIDE_ALL                    1204
#define IDC_LOAD_RUN                    1205
#define IDC_BOMSL_REMOVE_BUTTON         1205
#define IDC_UNCOMMIT                    1205
#define IDC_ACF_2DEO_BROWSE             1205
#define IDC_COLOUR_TEXT                 1205
#define IDC_BOMSL_REMOVE_ALL_BUTTON     1206
#define IDC_SAVE_REPORT                 1206
#define IDC_SELECT_SIMILAR              1206
#define IDC_STORAGE_EXPORT              1206
#define IDC_COLOUR_TOE_BOARD_CLIP       1206
#define IDC_COLOUR_STAIR_RAIL_STOPEND   1207
#define IDC_PRINT_BUTTON                1208
#define IDC_COLOUR_STAIR_RAIL           1208
#define IDC_COLOUR_LADDER_PUTLOG        1209
#define IDC_BOMS_SUMMARY_BUTTON         1210
#define IDC_COLOUR_STANDARD_CONNECTOR   1210
#define IDC_CBFHEAD                     1211
#define IDC_COLOUR_TRANSOM              1211
#define IDC_CBSHEAD                     1212
#define IDC_COLOUR_LEDGER               1212
#define IDC_CBFFOOTER                   1213
#define IDC_COLOUR_CORNER_STAGE_BOARD   1213
#define IDC_CBSFOOTER                   1214
#define IDC_COLOUR_STAGE_BOARD          1214
#define IDC_CBFCORPO                    1215
#define IDC_COLOUR_LAPBOARD             1215
#define IDC_CBSCORPO                    1216
#define IDC_COLOUR_DECKING_PLANK        1216
#define IDC_EDHEAD                      1217
#define IDC_COLOUR_CHAIN_LINK           1217
#define IDC_EDPAGE                      1218
#define IDC_COLOUR_BRACING              1218
#define IDC_EDFOOTER                    1219
#define IDC_COLOUR_MESH_GUARD           1219
#define IDC_ED_MMSX                     1220
#define IDC_COLOUR_TOE_BOARD            1220
#define IDC_ED_MMDOWN                   1221
#define IDC_COLOUR_MID_RAIL             1221
#define IDC_ED_MMUP                     1222
#define IDC_COLOUR_RAIL                 1222
#define IDC_ED_MMDX                     1223
#define IDC_COLOUR_TIE_CLAMP_90DEGREE   1223
#define IDC_TAB1                        1224
#define IDC_COLOUR_TIE_CLAMP_YOKE       1224
#define IDC_BT_PRINTOPT                 1225
#define IDC_COLOUR_TIE_CLAMP_MASONARY   1225
#define IDC_TEXT1                       1226
#define IDC_COLOUR_TIE_CLAMP_COLUMN     1226
#define IDC_PAGES                       1227
#define IDC_COLOUR_TIE_TUBES            1227
#define IDC_PROGRESS1                   1228
#define IDC_COLOUR_TIE_BAR              1228
#define IDC_ANIMATE1                    1229
#define IDC_COLOUR_SOLEBOARDS           1229
#define IDC_PC                          1230
#define IDC_COLOUR_JACKS                1230
#define IDC_COLOUR_STANDARDS_OPEN_END   1231
#define IDC_SETSTAGES_LOWER_LEVEL_COMBO 1232
#define IDC_COLOUR_STANDARDS            1232
#define IDC_COLOUR_LADDER               1233
#define IDC_COLOUR_STAIR                1234
#define IDC_BAY_LENGTH_COMBO2           1235
#define IDC_COLOUR_HOPUP_BRACKETS       1235
#define IDC_COLOUR_SHADE_CLOTH          1236
#define IDC_COLOUR_MATRIX_RL_SPAN       1237
#define IDC_COLOUR_MATRIX_RL_MAJOR      1238
#define IDC_COLOUR_MATRIX_RL_MINOR      1239
#define IDC_COLOUR_MATRIX_RL_TEXT       1240
#define IDC_COLOUR_CROSSHAIR_ARC        1241
#define IDC_STANDARD_COMBO_CTRL         1241
#define IDC_COLOUR_CROSSHAIR            1242
#define IDC_ASSIGN_STAGENAME_COMBO      1243
#define IDC_COLOUR_BAY_2400             1243
#define IDC_COLOUR_BAY_1800             1244
#define IDC_BAYS_PER_TIE_BAY_LBL        1245
#define IDC_COLOUR_BAY_1200             1245
#define IDC_BAYS_PER_BRACING_BAY_LBL    1246
#define IDC_COLOUR_BAY_0800             1246
#define IDC_BAY_FIT_LBL                 1247
#define IDC_COLOUR_MATRIX_LEVEL_LINES   1247
#define IDC_DISTANCE_FROM_WALL_LBL      1248
#define IDC_COLOUR_MATRIX_LEVEL_TEXT    1248
#define IDC_DISTANCE_FROM_WALL_UINTS_LBL 1249
#define IDC_COLOUR_COMMITTED            1249
#define IDC_FIT_GROUP_BOX               1250
#define IDC_COLOUR_PARTIAL_COMMITTED    1250
#define IDC_STAGES_POSITON_SOUTH        1251
#define IDC_STAGES_POSITON_DECKS        1252
#define IDC_BAY_RL_CHANGE_PIC           1256
#define IDC_BAYS_SELECTED_LBL           1257
#define IDC_BAY_NUMBER_START_LBL        1258
#define IDC_BAY_NUMBER_END_LBL          1259
#define IDC_BAY_WIDTH_END_LBL           1260
#define IDC_BAY_WIDTH_START_LBL         1261
#define IDC_SEPARATION_DISTANCE_LBL     1262
#define IDC_STAGE_COMBO                 1263
#define IDC_QUANTITY_SPIN               1265
#define IDC_AMALGAMATE                  1271
#define IDC_HEIGHT_INNER                1274
#define IDC_HEIGHT_OUTER                1277
#define IDC_MATRIX_SECTIONS_LIST        1279
#define IDC_SOLEBOARD_INNER             1280
#define IDC_SOLEBOARD_OUTER             1281
#define IDC_BAYS                        1282
#define IDC_USE_MIDRAIL_WITH_CHAIN      1283
#define IDC_LEDGERS_EVERY_METRE         1284
#define IDC_CT_DECKING_PLANK            1285
#define IDC_COLOUR_BY_STAGE_LEVEL       1286
#define IDC_CT_LAPBOARD                 1286
#define IDC_MOVING_DECK                 1287
#define IDC_CT_STAGE_BOARD              1287
#define IDC_VERSION_NUMBER              1288
#define IDC_CT_LEDGER                   1288
#define IDC_HARDWARE_LOCK_ID            1289
#define IDC_CT_TRANSOM                  1289
#define IDC_CT_MESH_GUARD               1290
#define IDC_COPYRIGHT_MESSAGE           1291
#define IDC_CT_RAIL                     1291
#define IDC_CT_MID_RAIL                 1292
#define IDC_CONNECT_NNE                 1292
#define IDC_CT_TOE_BOARD                1293
#define IDC_CONNECT_ENE                 1293
#define IDC_CT_CHAIN_LINK               1294
#define IDC_CONNECT_ESE                 1294
#define IDC_CT_SHADE_CLOTH              1295
#define IDC_CONNECT_SSE                 1295
#define IDC_CT_TIE_TUBE                 1296
#define IDC_CONNECT_SSW                 1296
#define IDC_CT_TIE_CLAMP_COLUMN         1297
#define IDC_CONNECT_WSW                 1297
#define IDC_CT_TIE_CLAMP_MASONARY       1298
#define IDC_CONNECT_WNW                 1298
#define IDC_CT_TIE_CLAMP_YOKE           1299
#define IDC_CONNECT_NNW                 1299
#define IDC_CT_TIE_CLAMP_90DEGREE       1300
#define IDC_STANDARD_NE                 1300
#define IDC_CT_BRACING                  1301
#define IDC_STANDARD_SE                 1301
#define IDC_CT_STAIR                    1302
#define IDC_STANDARD_NW                 1302
#define IDC_CT_LADDER                   1303
#define IDC_STANDARD_SW                 1303
#define IDC_CT_STANDARD                 1304
#define IDC_PLANK1                      1304
#define IDC_CT_STANDARD_OPENEND         1305
#define IDC_STANDARD_NONE               1305
#define IDC_CT_JACK                     1306
#define IDC_PLANK2                      1306
#define IDC_CT_SOLEBOARD                1307
#define IDC_PLANK3                      1307
#define IDC_CT_HOPUP_BRACKET            1308
#define IDC_PLANK4                      1308
#define IDC_CT_CORNER_STAGE_BOARD       1309
#define IDC_PLANK5                      1309
#define IDC_CT_TEXT                     1310
#define IDC_PLANK6                      1310
#define IDC_CT_TIE_BAR                  1311
#define IDC_PLANK7                      1311
#define IDC_CT_STANDARD_CONNECTOR       1312
#define IDC_CT_LADDER_PUTLOG            1313
#define IDC_ROOF_PROTECTION             1314
#define IDC_CT_STAIR_RAIL               1314
#define IDC_ROOF_PROTECTION_1500        1315
#define IDC_CT_STAIR_RAIL_STOPEND       1315
#define IDC_PLANK8                      1315
#define IDC_ROOF_PROTECTION_2000        1316
#define IDC_CT_TOE_BOARD_CLIP           1316
#define IDC_PLANK9                      1316
#define IDC_FILTER_STRING               1317
#define IDC_PLANK10                     1317
#define IDC_MATCHING_ELEMENTS           1318
#define IDC_FILTER                      1319
#define IDC_AVI                         1320
#define IDC_PIC                         1321
#define IDC_LONGER_BRACING              1322
#define IDC_EXTRA_COMPONENTS_LISTCONTROL 1327
#define IDC_MATCH_DECK_TO_LEVELS        1328
#define IDC_REVISION_NUMBER             1329
#define IDC_ESTIMATOR                   1331
#define IDC_REVISION_NOTES              1332
#define IDC_REVISION_DATE               1333
#define IDC_VISUALS_VISIBLE             1334
#define IDC_PROGRESS_CTRL               1346
#define IDC_DIMENSIONS_LENGTH_ACTUAL    1353
#define IDC_DIMENSIONS_WIDTH_ACTUAL     1354
#define IDC_DIMENSIONS_HEIGHT_ACTUAL    1355
#define IDC_DIMENSIONS_WEIGHT_ACTUAL    1356
#define IDC_VISUALS_ACTUAL_COMP_AVAIL   1357
#define IDC_OTHER_HIRE                  1359
#define IDC_OTHER_SALE                  1360
#define IDC_VISUALS_COMPONENT_COLOUR    1361
#define IDC_DETAILS_TYPE                1363
#define IDC_DETAILS_MATERIAL            1364
#define IDC_DIMENSIONS_LENGTH_COMMON    1365
#define IDC_DETAILS_DESCRIPTION         1366
#define IDC_SL_STAGE_COMBO              1367
#define IDC_SL_LEVEL_COMBO              1368
#define IDC_OTHER_SYSTEM                1369
#define IDC_DETAILS_PART_NUMBER         1370
#define IDC_DETAILS_CHANGE_PART_NO      1371
#define IDC_VC_EDIT_PIC                 1372
#define IDC_VC_INSERT_PIC               1373
#define IDC_EDIT1                       1376
#define IDC_NEW_COMPONENT               1377
#define IDC_EDIT2                       1378
#define IDC_EDIT3                       1379
#define IDC_EDIT4                       1380
#define IDC_EDIT5                       1381
#define IDC_EDIT6                       1382
#define IDC_EDIT7                       1383
#define IDC_FILENAME_3D                 1384
#define IDC_EDIT9                       1385
#define IDC_BROWSE_3D_FILENAME          1386
#define IDC_FILENAME_2D                 1387
#define IDC_BROWSE_2D_FILENAME          1388
#define IDC_FILENAME_2DEO               1389
#define IDC_BROWSE_2DEO_FILENAME        1390
#define IDC_CALCULATE_ROLLS             1391
#define IDC_AREA_PER_ROLL               1392
#define IDC_BUTTON3                     1393
#define IDC_EDIT12                      1395
#define IDC_ACF_2D                      1396
#define IDC_ACF_2DEO                    1397
#define IDC_HIDE                        1397
#define IDC_STAGE_LEVEL_LIST            1398
#define IDC_SHOW                        1399
#define IDC_STAGE_LEVEL                 1400
#define IDC_SHOW_HIDE                   1401
#define IDC_DIM_HEIGHT                  1402
#define IDC_DIM_LENGTH_ACTUAL           1406
#define IDC_DIM_WIDTH                   1407
#define IDC_DIM_WEIGHT                  1408
#define IDC_DIM_LENGTH_COMMON           1409
#define IDC_DETAILS_SELECT_PART_NO      1411
#define IDC_ACF_3D                      1412
#define IDC_ACF_3D_BROWSE               1413
#define IDC_DELETE                      1416
#define IDC_APPLY_CHANGES               1418
#define IDC_CLOSE                       1419
#define IDC_OTHER_USE_SALE_PRICE        1420
#define IDC_OTHER_PER_ROLL              1421
#define IDC_MAIN_LABEL                  1422
#define IDC_AREA_SPINNER                1423
#define IDC_CALC_PER_METRE              1425
#define IDC_CALC_PER_ROLL               1426
#define IDC_ROUNDING_DEVISOR            1428
#define IDC_SELECT_PART_NUMBER          1429
#define IDC_PRODUCT_CODE                1430
#define IDC_STORAGE_IMPORT              1431
#define IDC_RESET_COLOUR                1432
#define IDC_BRACE_LENGTH_2400           1434
#define IDC_BRACE_LENGTH_1800           1435
#define IDC_OPEN_ENDED                  1435
#define IDC_BRACE_LENGTH_1200           1436
#define IDC_BRACE_LENGTH_0700           1437
#define ID_AUTOBUILD_BAY_DETAILS_BUTTON 40020
#define ID_RUN_DETAILS_BUTTON           40021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         110
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
